apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
  namespace: production
  labels:
    app: todo-app
    tier: backend
spec:
  selector:
    matchLabels:
      app: todo-app
      tier: backend
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-app
        tier: backend
    spec:
      containers:
      - name:  todo-app
        image:  yusufluai/todo-app_server:IMAGE_TAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 400Mi
        env:
          - name: MONGO_URL
            value: "mongodb://mongo-service.production:27017"
        ports:
        - containerPort: 4000
          protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname   
      restartPolicy: Always