apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc-frontend
spec:
  selector:
    app: todo-app
    tier: frontend
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort
  ports:
  - name: todo-app
    protocol: TCP
    port: 3000
    targetPort: 3000