apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: todo-app
    tier: database
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017