apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow

