apiVersion: apps/v1
kind: Deployment
metadata:
  name:  todo-app-database
  namespace: staging
  labels:
    app: todo-app
    tier: database
spec:
  selector:
    matchLabels:
      app: todo-app
      tier: database
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  todo-app
        tier: database
    spec:
      containers:
      - name:  mongodb
        image:  mongo:3.6.19-xenial
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 27017
      restartPolicy: Always
    
