apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: MYAPP
  namespace: staging
  labels:
    app: MYAPP
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  