- name: jenkins test
  ansible.builtin.jenkins_job:
    name: todo-app
    config: 
    enabled: present
    url:
    password:
    state:
    token:
    user:

- name: install jenkins plugin
  ansible.builtin.jenkins_plugin:
